### ISSUE TITLE
在浏览器进入 localhost:3000 后, 只显示 Not Found

### ISSUE THREAD

**Issue by osricwong** [baiyuze/koa-react-ssr-render#1]
你好

打 npm start 后, 
在浏览器进入 localhost:3000 后, 只显示 Not Found

**Comment by baiyuze** [comment]
我刚才在github上直接下载，执行npm run build ，再执行npm run start 直接启动了，并没有你所说的问题。

你看你的终端是不是报了什么错？如果报错了，你发下。

另外如果显示Not Found ,应该是没有找到具体HTML造成的，也有可能是路由配置不正确造成的。

**Comment by baiyuze** [comment]
> 你好
> 
> 打开npm start后，
> 在浏览器进入localhost：3000后，只显示未找到

我刚才在github上直接下载，执行npm run build，再执行npm run start直接启动了，并没有你所说的问题。

你看你的终端是不是报了什么错？如果报错了，你发下。

另外如果显示Not Found，应该是没有找到具体HTML造成的，也有可能是路由配置不正确造成的。

**Comment by baiyuze** [comment]
> 你好
> 
> 打开npm start后，
> 在浏览器进入localhost：3000后，只显示未找到

另外，我没有使用window电脑试过，不知道会不会有兼容问题。

你可以使用git bash终端启动试试。

**Comment by xiajinchun** [comment]
我这边也是，我用的 Mac， npm run build 和 npm run start 均未报错。

**Comment by baiyuze** [comment]
> 你好
> 
> 打 npm start 后,
> 在浏览器进入 localhost:3000 后, 只显示 Not Found

这个问题已经修复好了，你那边pull下
